name: deployment to gcp cloud storage

on:
  push:
    branches:
      - main

env:
  ARTIFACT_NAME: build-output
  BUILD_DIR: dist
  GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
  GCP_CDN_LOAD_BALANCER_NAME: ${{ secrets.GCP_CDN_LOAD_BALANCER_NAME }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Set Environment Variables
        run: |
          echo "VITE_MAP_CLIENT_ID=${{ secrets.VITE_MAP_CLIENT_ID }}" >> $GITHUB_ENV
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> $GITHUB_ENV
          echo "VITE_MAP_STYLE_ID=${{ secrets.VITE_MAP_STYLE_ID }}" >> $GITHUB_ENV
          echo "VITE_IMAGE_UPLOAD_MAX_SIZE=${{ secrets.VITE_IMAGE_UPLOAD_MAX_SIZE }}" >> $GITHUB_ENV
          echo "VITE_CLOUDFRONT_URL=${{ secrets.VITE_CLOUDFRONT_URL }}" >> $GITHUB_ENV
          echo "VITE_KAKAO_REST_API_KEY=${{ secrets.VITE_KAKAO_REST_API_KEY }}" >> $GITHUB_ENV
          echo "VITE_KAKAO_REDIRECT_URI=${{ secrets.VITE_KAKAO_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "VITE_NAVER_CLIENT_ID=${{ secrets.VITE_NAVER_CLIENT_ID }}" >> $GITHUB_ENV
          echo "VITE_NAVER_CLIENT_SECRET=${{ secrets.VITE_NAVER_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "VITE_NAVER_REDIRECT_URI=${{ secrets.VITE_NAVER_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "VITE_GOOGLE_CLIENT_SECRET=${{ secrets.VITE_GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "VITE_GOOGLE_REDIRECT_URI=${{ secrets.VITE_GOOGLE_REDIRECT_URI }}" >> $GITHUB_ENV

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.BUILD_DIR }}

  cd:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        id: 'checkout'
        uses: 'actions/checkout@v4'

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.BUILD_DIR }}

      - name: Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Upload Folder
        id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: ${{ env.BUILD_DIR }}
          destination: ${{ env.GCP_BUCKET_NAME }}
          parent: false

      - name: Invalidate Cloud CDN Cache
        run: |
          gcloud compute url-maps invalidate-cdn-cache ${{ env.GCP_CDN_LOAD_BALANCER_NAME }} \
            --path "/*"
